version: "3"
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  hash:
    image: monitor
    ports:
      - 8080:8080