version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  alertmanager:
    image: prometheus/alertmanager:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
